from pathlib import Path
from ultralytics import YOLO


# ============================================================
# 1. PATHS
# ============================================================

model_path = Path(
    "../YOLO Train Custom Detector/runs/plate_detector/weights/best.pt"
).resolve()

dataset_yaml = Path(
    "../Plate Detection Dataset/data.yaml"
).resolve()


# ============================================================
# 2. CHECK FILES
# ============================================================

if not model_path.exists():
    raise FileNotFoundError(
        f"Model not found: {model_path}"
    )

if not dataset_yaml.exists():
    raise FileNotFoundError(
        f"Dataset configuration not found: {dataset_yaml}"
    )


# ============================================================
# 3. LOAD TRAINED MODEL
# ============================================================

model = YOLO(str(model_path))

print("========== YOLO MODEL VALIDATION ==========")
print("Model:", model_path)
print("Dataset:", dataset_yaml)


# ============================================================
# 4. VALIDATE MODEL
# ============================================================

metrics = model.val(
    data=str(dataset_yaml),
    split="test",
    imgsz=640,
    batch=4,
    conf=0.25,
    device="cpu",
    plots=True,
    verbose=True
)


# ============================================================
# 5. DISPLAY RESULTS
# ============================================================

print("\n========================================")
print("VALIDATION COMPLETE")
print("========================================")

print(f"mAP50:     {metrics.box.map50:.4f}")
print(f"mAP50-95:  {metrics.box.map:.4f}")

print("\nPer-class mAP50:")

for class_id, score in enumerate(metrics.box.ap50):
    class_name = model.names[class_id]
    print(f"{class_name}: {score:.4f}")


# ============================================================
# 6. FINAL MESSAGE
# ============================================================

print("\nValidation results were generated by Ultralytics.")
print("Check the validation output directory for plots.")